### PR TITLE
[v2.7] Add support for rotating worker nodes after creating an etcd snapshot

### PR DESCRIPTION
**Pull request by markusewalker**
## Issue:  [Automate rotating nodes after creating an etcd snapshot](https://github.com/rancher/qa-tasks/issues/989)

v2.7 backport of https://github.com/rancher/shepherd/pull/59

### CODE REVIEW

**Review by Josh-Diamond — APPROVED** [review]

**Review by slickwarren — APPROVED** [review]

**Review by slickwarren — APPROVED** [review]

**Comment by caliskanugur** [comment]
Does this one need a rebase?

**Comment by markusewalker** [comment]
@caliskanugur just rebased, sorry I thought I did earlier.

**Review by igomez06 — APPROVED** [review]
LGTM

**Review by slickwarren — APPROVED** [review]

**Review by caliskanugur — APPROVED** [review]
LGTM

**Pull request merged**
