### PR TITLE
[2.8] Adding extensions for rbac checks

### PR DESCRIPTION
**Pull request by anupama2501**
Back port https://github.com/rancher/shepherd/pull/16

### CODE REVIEW

**Review by caliskanugur — COMMENTED** [review]
There are two diffs in this PR between 2.9 PR. One is config, and the other is rbac.go in rbac extensions doesn't have a setup user function. Are these expected?

**Review by igomez06 — APPROVED** [review]
LGTM

**Comment by anupama2501** [comment]
hey @caliskanugur this branch is behind a commit as I was testing the 2.9 branch with latest changes and making sure it works with the current PRs. Updated this PR now.

**Review by caliskanugur — APPROVED** [review]
Looks good to me

**Review by Priyashetty17 — APPROVED** [review]

**Pull request merged**
