### PR TITLE
[2.7] Add functional tfexec client

### PR DESCRIPTION
**Pull request by git-ival**
Backport of PR #19

### CODE REVIEW

**Comment by git-ival** [comment]
In order to prevent potential complications with the module versions used in rancher/rancher 2.7 we are opting to move this PR into a draft state, in case this client is needed for 2.7 testing in the future.

**Comment by git-ival** [comment]
Updated go.mod to match dependencies from rancher/rancher `release/v2.7` line

**Review by caliskanugur — COMMENTED** [review]
Looks good to me, could we get a squash for this one?

**Review by caliskanugur — APPROVED** [review]
Looks good to me

**Review by igomez06 — APPROVED** [review]
LGTM

**Pull request merged**
