### PR TITLE
[backport 2.8] Snapshot retention

### PR DESCRIPTION
**Pull request by susesgartner**
Backport of https://github.com/rancher/shepherd/pull/75/files#diff-06c48b25669b482489241f1d6d4e4bd05d5d3e3551b33dc61b49675d9e15594b

### CODE REVIEW

**Review by markusewalker — APPROVED** [review]
LGTM

**Review by igomez06 — COMMENTED** [review]
Update, and rebase please

**Comment by susesgartner** [comment]
Rebased

**Comment by caliskanugur** [comment]
It's ~40 commits behind, could you rebase it again?

**Review by igomez06 — APPROVED** [review]
LGTM

**Review by caliskanugur — APPROVED** [review]
LGTM

**Pull request merged**
