### PR TITLE
[backport 2.7] Snapshot Retention test

### PR DESCRIPTION
**Pull request by susesgartner**
Backport of [issue ](https://github.com/rancher/shepherd/pull/75/files#diff-06c48b25669b482489241f1d6d4e4bd05d5d3e3551b33dc61b49675d9e15594b)

### CODE REVIEW

**Review by markusewalker — APPROVED** [review]
LGTM

**Review by igomez06 — COMMENTED** [review]
Update, and rebase please. Also can you give it a proper title?

**Comment by susesgartner** [comment]
Rebased and updated the title

**Comment by caliskanugur** [comment]
Same for this one too, it needs another rebase

**Review by igomez06 — APPROVED** [review]
LGTM

**Review by caliskanugur — APPROVED** [review]
LGTM

**Pull request merged**
