### PR TITLE
[V2.7] clusterrepo client update

### PR DESCRIPTION
**Pull request by igomez06**

### CODE REVIEW

**Review by floatingman — APPROVED** [review]
Looks good!

**Review by caliskanugur — APPROVED** [review]
Looks good to me

**Comment by igomez06** [comment]
Need to hold of on merging this as this news version bumps in the k8s packages. Will confirm at a later date.

**Comment by caliskanugur** [comment]
Is this one ready for review, (if yes) could we get a rebase?

**Comment by igomez06** [comment]
Accidentally closed PR.

**Review by caliskanugur — APPROVED** [review]
Looks good to me

**Pull request merged**
